# Generated by Django 5.2.7 on 2025-10-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='img_productos/'),
        ),
    ]
